### ISSUE TITLE
Numbers for 2021-04-26 seem to be wrong

### ISSUE THREAD

**Issue by edg-stg** [n0rdlicht/rki-vaccination-scraper#19]
e.g. 
Germany,DE,nation,sum_initial_moderna,3597780,83166711,7.260192121821434,2021-04-26
while on 2021-04-25:
Germany,DE,nation,sum_initial_moderna,1069222,83166711,7.166621029416445,2021-04-25
was 2.5 million less...
rki excel reports 1099371 on 2021-04-26

**Comment by n0rdlicht** [comment]
Will do a check on these. I noticed some irregularities with changes to the Excel towards the end of the week.
