### ISSUE TITLE
key sum_booster is missing (as of 2021-02-05) in csv files

### ISSUE THREAD

**Issue by edg-stg** [n0rdlicht/rki-vaccination-scraper#6]
but sum_booster_moderna and sum_booster_biontech are available

**Comment by n0rdlicht** [comment]
Will take a look in the evening. Should be an easy fix.

**Comment by n0rdlicht** [comment]
@edg-stg can you check if it shows up how you expected? The new keys should now be included. I will backfill the missing values in `data/de-vaccinations.csv` since 2021-02-05 in the evening based on the git history.

**Comment by edg-stg** [comment]
looks great and works fine. thanks!

**Comment by n0rdlicht** [comment]
Backfilling will need to happen over the weekend -> #8.
